### ISSUE TITLE
strm files containing an apostrophe 

### ISSUE THREAD

**Issue by ddurdle** [ddurdle/GDrive-for-KODI#101]
First scenario
video file name and strm file name contain an apostrophe:
Stephen King's Es.1080p.bluray.dca.mkv
Stephen King's Es.1080p.bluray.dca.mkv.strm
-> The error occurs
second scenario
I removed the apostrophe only from the strm file name, not from original video file, so
Stephen King's Es.1080p.bluray.dca.mkv
Stephen Kings Es.1080p.bluray.dca.mkv.strm
-> The error occurs
third scenario 
I removed the apostrophe from the strm file name, the original video file name and, consequentially, from the link in the .strm file, so
Stephen Kings Es.1080p.bluray.dca.mkv
Stephen Kings Es.1080p.bluray.dca.mkv.strm
-> playback works fine

**Comment by horstepipe** [comment]
hey
Talked to the Emby for Kodi dev because of the apostrophe problem. 
He brought a fix so Emby now encodes it with %27.
The problem still persists, but he is sure now that it is not an Emby for Kodi problem anymore.

Best regards

**Comment by horstepipe** [comment]
here is the error from Kodi log:

`12:06:45 T:5704   ERROR: gdrive: HTTP Error 400: Bad Request
12:06:45 T:5704   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: 'NoneType' object is not iterable
                                            Traceback (most recent call last):
                                              File "C:\Users\horstepipe\AppData\Roaming\Kodi\addons\plugin.video.gdrive\default.py", line 1277, in <module>
                                                (mediaURLs,package) = service.getPlaybackCall(None,title=title)
                                            TypeError: 'NoneType' object is not iterable
                                            -->End of Python script error report<--
12:06:45 T:6168   ERROR: Playlist Player: skipping unplayable item: 1, path [plugin://plugin.video.emby.movies/?dbid=1121&mode=play&id=939ac3d7feb3d7e640001cd3ced2eb6a&filename=The+Man+Who+Wasnt+There.480p.dvd.ac3.avi.strm]
`

**Comment by horstepipe** [comment]
fix unfortunately doesn't work, I'm getting:
`12:53:58 T:2060   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'sre_constants.error'>
                                            Error Contents: nothing to repeat
                                            Traceback (most recent call last):
                                              File "C:\Users\horstepipe\AppData\Roaming\Kodi\addons\plugin.video.gdrive\default.py", line 1458, in <module>
                                                (mediaURLs,package) = service.getPlaybackCall(None,title=title)
                                              File "C:\Users\horstepipe\AppData\Roaming\Kodi\addons\plugin.video.gdrive\resources\li​b\gdrive_api2.py", line 1307, in getPlaybackCall
                                                encodedTitle = re.sub('?', '\\?', encodedTitle)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\re.py", line 151, in sub
                                                return _compile(pattern, flags).sub(repl, string, count)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\re.py", line 244, in _compile
                                                raise error, v # invalid expression
                                            error: nothing to repeat
                                            -->End of Python script error report<--`

for every video

**Comment by ddurdle** [comment]
Fixed now on 0.8.33.  Fixed the issue last night and then tried to get
fancy and broke all videos.

Should be working now in 0.8.33 for ' and &.  ? and # filtering didn't
work, but I'm not sure if videos with those names are having problem in the
way you are invoking STRM.

**Comment by horstepipe** [comment]
apostrophe works now, thank you. But on titles with "&" I'm still getting the same error. 
"?" works fine, "#" doesn't but that's no big deal.
So now I just need to rename the titles with "&", this is way better than before, thank you!

**Comment by ddurdle** [comment]
promoted to stabe
